import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import awsconfig from './aws-exports'; // Import the aws-exports.js file generated by Amplify

import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

// Configure Amplify with the imported configuration
Amplify.configure(awsconfig);

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Measure performance if needed
reportWebVitals();
